[DEFAULT]
# system key is repeated from file1.ini with a different value
system = mac

[School]
# Name is a repeated key from file1.ini with a different value
Name = D.A.V
Location_of_School = Bengaluru

